version: '3.8'

services:
  bd:
    container_name: colev-api-bd
    image: mongo:5.0.9
    restart: unless-stopped
    networks:
      - colev-api
    volumes:
      - ./basededatos:/data/db
    ports:
      - ${BD_PUERTO}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${BD_USUARIO}
      MONGO_INITDB_ROOT_PASSWORD: ${BD_CLAVE}
      MONGO_INITDB_DATABASE: covid

  cache:
    container_name: colev-api-cache
    image: redis:7.0-alpine
    restart: unless-stopped
    networks:
      - colev-api
    ports:
      - ${CACHE_PUERTO}:6379

networks:
  colev-api:
