version: '3.8'

services:
  bd:
    container_name: colev-api-bd
    image: mongo
    restart: unless-stopped
    networks:
      - colev-api
    volumes:
      - ./basededatos:/data/db
    ports:
      - ${BD_PUERTO}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${BD_USUARIO}
      MONGO_INITDB_ROOT_PASSWORD: ${BD_CLAVE}
      MONGO_INITDB_DATABASE: covid

  cache:
    container_name: colev-api-cache
    image: redis:6.2-alpine
    restart: unless-stopped
    networks:
      - colev-api
    ports:
      - ${CACHE_PUERTO}:6379

  mongo-express:
    container_name: colev-api-mongoexpress
    image: mongo-express
    restart: unless-stopped
    networks:
      - colev-api
    ports:
      - 8081:8081
    depends_on:
      - bd
      - cache
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${BD_USUARIO}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${BD_CLAVE}
      ME_CONFIG_MONGODB_SERVER: bd
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_USUARIO}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_CLAVE}

networks:
  colev-api:
